<a href="https://colab.research.google.com/github/gitanujjain/MLdataset/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [3]:
my_arr=np.arange(1000000)

In [4]:
my_list= list(range(10000))

In [5]:
data=np.random.randn(2,3)

In [6]:
data

array([[ 1.20951005, -0.06304275, -0.72147391],
       [ 1.20241562, -1.00153723,  0.33450199]])

In [7]:
data*10

array([[ 12.09510054,  -0.63042746,  -7.21473909],
       [ 12.02415623, -10.01537231,   3.34501992]])

In [8]:
data+data

array([[ 2.41902011, -0.12608549, -1.44294782],
       [ 2.40483125, -2.00307446,  0.66900398]])

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

In [11]:
data1=[6,7.5,8,0,1]
arr1=np.array(data1)

In [12]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)

In [14]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr2.ndim

2

In [16]:
arr2.shape

(2, 4)

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int64')

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
np.empty((2,3,2))

array([[[4.72392221e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [22]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
arr1=np.array([1,2,3], dtype=np.float64)

In [5]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [6]:
arr1.dtype

dtype('float64')

In [7]:
arr2.dtype

dtype('int32')

In [8]:
arr= np.array([1,2,3,4,5])

In [9]:
arr.dtype

dtype('int64')

In [10]:
float_arr = arr.astype(np.float64)

In [11]:
float_arr.dtype

dtype('float64')

In [12]:
arr= np.array([3.7, -1.2, -2.6,0.5,12.9,10.1])

In [13]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [14]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [ ]:
import

In [16]:
numeric_string = np.array(['1.25','-9.6','42'], dtype=np.string_)

In [17]:
numeric_string.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [20]:
int_array=np.arange(10)

In [21]:
calibers= np.array([.22,.279, .379,0.380,.44,.55], dtype=np.float64)

In [24]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [25]:
empty_unit32=np.empty(6)

In [28]:
empty_unit32


array([0.22 , 0.279, 0.379, 0.38 , 0.44 , 0.55 ])

In [34]:
arr= np.array([[1,2,3,4,5],[6,7,8,8,9]])

In [35]:
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 8, 9]])

In [36]:
arr*arr

array([[ 1,  4,  9, 16, 25],
       [36, 49, 64, 64, 81]])

In [37]:
arr+100

array([[101, 102, 103, 104, 105],
       [106, 107, 108, 108, 109]])

In [38]:
arr-arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [39]:
1/arr

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.125     , 0.11111111]])

In [41]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 2.82842712, 3.        ]])

In [42]:
arr2=np.array([1,2,3,4,5,6])
arr2%2==0

array([False,  True, False,  True, False,  True])

In [43]:
arr2=np.array([[0,4,1],[7.,2.,12]])

In [44]:
arr2>arr

ValueError: operands could not be broadcast together with shapes (2,3) (2,5) 

INdexing & slcing

In [45]:
arr=np.arange(10)

In [46]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr[5]

5

In [49]:
arr[5:8]

array([5, 6, 7])

In [50]:
arr[5:8]=12

In [51]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])